In [10]:
#TASK-3 CUSTOMER CHURN PREDICTION EXECUTION
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

data = pd.read_csv(r'C:\Users\nehaa\Desktop\int\task3\archive (4)\Churn_Modelling.csv')
print("CUSTOMER CHURN PREDICTION")
print(data.isnull().sum())
encoder = LabelEncoder()
data['Geography'] = encoder.fit_transform(data['Geography'])
data['Gender'] = encoder.fit_transform(data['Gender'])
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

scaler = StandardScaler()
scale_cols = ['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'EstimatedSalary']
data[scale_cols] = scaler.fit_transform(data[scale_cols])


X = data.drop('Exited', axis=1)
y = data['Exited']
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression()
model.fit(Xtrain, ytrain)
ypred = model.predict(Xtest)
print("Logistic Regression Results:")
print(classification_report(ytest, ypred))
print(confusion_matrix(ytest, ypred))
print("Accuracy:", accuracy_score(ytest, ypred))

CUSTOMER CHURN PREDICTION
RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64
Logistic Regression Results:
              precision    recall  f1-score   support

           0       0.83      0.97      0.89      1607
           1       0.60      0.18      0.28       393

    accuracy                           0.82      2000
   macro avg       0.71      0.58      0.59      2000
weighted avg       0.78      0.82      0.77      2000

[[1559   48]
 [ 321   72]]
Accuracy: 0.8155


In [3]:
model = GradientBoostingClassifier()
model.fit(Xtrain, ytrain)
ypred = model.predict(Xtest)
print("\nGradient Boosting Classifier Results:")
print(classification_report(ytest, ypred))
print(confusion_matrix(ytest, ypred))
print("Accuracy:", accuracy_score(ytest, ypred))


Gradient Boosting Classifier Results:
              precision    recall  f1-score   support

           0       0.88      0.96      0.92      1607
           1       0.75      0.47      0.58       393

    accuracy                           0.86      2000
   macro avg       0.82      0.71      0.75      2000
weighted avg       0.86      0.86      0.85      2000

[[1547   60]
 [ 210  183]]
Accuracy: 0.865


In [4]:
model = RandomForestClassifier()
model.fit(Xtrain, ytrain)
ypred = model.predict(Xtest)
print("\nRandom Forest Classifier Results:")
print(classification_report(ytest, ypred))
print(confusion_matrix(ytest, ypred))
print("Accuracy:", accuracy_score(ytest, ypred))


Random Forest Classifier Results:
              precision    recall  f1-score   support

           0       0.88      0.97      0.92      1607
           1       0.78      0.46      0.58       393

    accuracy                           0.87      2000
   macro avg       0.83      0.71      0.75      2000
weighted avg       0.86      0.87      0.85      2000

[[1555   52]
 [ 213  180]]
Accuracy: 0.8675
